- hosts: all
  become: yes
  tasks:
    - name: Install packages
      package:
        name: "{{item}}"
        state: latest
      with_items:
        - httpd
        - httpd-devel
        - gcc
      when: ansible_distribution == 'CentOS'