- hosts: all
  become: yes
  tasks:
    - name: print something
      debug:
        msg: " NAME = {{item.name}} Value = {{item.value}}"
      with_items:
        - { name: kernel.shmmni, value: 4096 }